# === Core settings ===
taxon: "Gastropoda"              # scientific name or "txidXXXXX"
library_strategy: "RNA-Seq"    # e.g. RNA-Seq, WGS, ChIP-Seq
layout: "PAIRED"               # SINGLE or PAIRED
tissue_keywords:
  - brain
  - ganglia
  - venom
  - CNS
  - nervous
  - ganglion
  - sensory
  - tentacle
  - rhinophore
  - head
developmental_stage: ""   # e.g. embryo, juvenile, adult
sex: ""                  # male, female
min_read_length: 100            # minimum average read length (bp)

# === Size caps (GB) ===
max_species_data_gb: 60        # cap per species
max_project_data_gb: 20        # cap per BioProject

# === Parallelism & resources ===
max_parallel_species: 4        # number of species to process at once
download_threads: null         # auto-computed if null

# === Dry-run & test mode ===
dry_run: false                 # preview only, no downloads
test_mode: false               # limit to first N species & runs
test_limit_species: 1
test_limit_runs: 5

# === Resume & caching ===
output_dir: "/scratch/sra_data"
cache_dir: "./cache"           # where taxonomy & metadata caches live

# === Compression & validation ===
gzip_fastq: true
use_pigz: true                 # use pigz if available
validate_fastq: false           # check header counts vs SRA spots

# === Plotting & reporting ===
reports_dir: "reports"         # relative to output_dir
top_n_species_plot: 25

# === Logging ===
log_file: "pipeline.log"
